import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { StaleWhileRevalidate } from 'workbox-strategies'

// Precache all assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST)

// Cache API requests
registerRoute(
  ({ url }) => url.origin === 'http://localhost:5000',
  new StaleWhileRevalidate({
    cacheName: 'api-cache'
  })
)

// Cache other assets
registerRoute(
  ({ request }) => request.destination === 'image' ||
                   request.destination === 'style' ||
                   request.destination === 'script',
  new StaleWhileRevalidate({
    cacheName: 'assets-cache'
  })
)
